### ISSUE TITLE
Infer newlines from content instead of Environment.NewLine

### ISSUE THREAD

**Issue by tuantu-ubidata** [DonZoeggerle/ediFabric#25]
Hi,

Thanks for the library, it's a real time saver!

I ran into this problem where I run on a Windows box and the file I'm parsing contains `LF` as new lines, whereas Windows uses `CRLF` to represent new lines.

It lead to this exception:

```
2016-03-24 19:55:23.2838|ERROR|TestEdiParsing.Program|System.ArgumentNullException: Value cannot be null.
Parameter name: ediSegment
   at EdiFabric.Framework.EdiHelper.GetSegmentName(String ediSegment, InterchangeContext interchangeContext) in D:\work\TestEdiParsing\ediFabric\Framework\EdiHelper.cs:line 199
   at EdiFabric.Framework.Envelopes.InterchangeLexer.Analyze() in D:\work\TestEdiParsing\ediFabric\Framework\Envelopes\InterchangeLexer.cs:line 95
   at EdiFabric.Framework.Envelopes.Edifact.Interchange.LoadFrom(Stream ediStream, String definitionsAssemblyName) in D:\work\TestEdiParsing\ediFabric\Framework\Envelopes\Edifact\Interchange.cs:line 78
   at TestEdiParsing.Program.Main(String[] args) in D:\work\TestEdiParsing\TestEdiParsing\Program.cs:line 31
```
(use sources from release 6.7.0 to match line numbers)

I inspected the code and I saw that the `EdiHelper.GetEdiSegments` was using `Environment.NewLine` ([line 114](https://github.com/DonZoeggerle/ediFabric/blob/4c596eea8f90ddd1a6bc4b20c0123c21a841a525/Framework/EdiHelper.cs#L114) for example) and it turned out that replacing `LF` with `CRLF` in the content I was parsing fixed the issue.

So I would suggest to either:
* infer the new line representation from the contents
* or add some option parameter to specify the kind of new line present in the content

Of course, the second option makes less sense as then the calling code can just alter the content to use the platform's representation of new lines, like I did, but I figured it would be a nice thing to have.

Thanks again for the library!

Cheers.

**Comment by DonZoeggerle** [comment]
Thank you for raising this, it's been fixed in release 6.7.1
