### ISSUE TITLE
Parse INVOIC D96A, Asterisk character

### ISSUE THREAD

**Issue by hayo1985** [DonZoeggerle/ediFabric#40]
We currently have an import of INVOIC D96A, containing an Asterisk character in the NAD C080, D3036 part. According to what I read this should be OK is in the Level A Character Set. 

When we load it with 6.8.3 with asterisk we get:

`EdiFabric.Framework.Exceptions.ParsingException: Value cannot be null.
Parameter name: dataElement ---> System.ArgumentNullException: Value cannot be null.
Parameter name: dataElement
   at EdiFabric.Framework.MessageLexer.GetComponentDataElements(String dataElement, Separators separators)
   at EdiFabric.Framework.ParseNodeExtensions.ParseSegment(ParseNode parseNode, String line, Separators separators)
   at EdiFabric.Framework.MessageLexer.Analyze(List`1 segments, Separators separators, Type type, String rulesAssemblyName)
   at EdiFabric.Framework.Readers.EdiReader.Read(Action`1 collect)
   --- End of inner exception stack trace ---`

When loading it with 6.7.3 we get:
The element 'C_C080_2' in namespace 'www.edifabric.com/edifact' has incomplete content. List of possible elements expected: 'D_3036_1' in namespace 'www.edifabric.com/edifact'.
The element 'S_NAD_2' in namespace 'www.edifabric.com/edifact' has invalid child element 'C_C080_2' in namespace 'www.edifabric.com/edifact'. List of possible elements expected: 'C_C059_2, D_3164_6, D_3229_7, D_3251_8, D_3207_9' in namespace 'www.edifabric.com/edifact'.

Neither behavior is as expected. If I use the release characters it parses correctly however, it shouldn't need release characters. 

Attached is the file
[39994_INVOIC_20161109230134_016_v1.txt](https://github.com/DonZoeggerle/ediFabric/files/603721/39994_INVOIC_20161109230134_016_v1.txt)

**Comment by hayo1985** [comment]
Updated to 6.8.6 and this resolved the issue.
