### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection.  Parameter name: index 

### ISSUE THREAD

**Issue by aseif83** [DonZoeggerle/ediFabric#58]
when i try to open Baplie EDI file,edifabric dll throw ParsingException "Index was out of range. Must be non-negative and less than the size of the collection.  Parameter name: index "
Stack Trace
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Collections.ObjectModel.ReadOnlyCollection`1.System.Collections.Generic.IList<T>.get_Item(Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at EdiFabric.Framework.Readers.EdiReaderExtensions.ParseSegment(ParseNode parseNode, String line, Separators separators, MessageErrorContext errorContext)
   at EdiFabric.Framework.Readers.EdiReaderExtensions.Analyze(List`1 segments, Separators separators, MessageContext messageContext)
   at EdiFabric.Framework.Readers.EdifactReader.ProcessSegment(String segment)
   at EdiFabric.Framework.Readers.EdiReader.Read()

kindly find edi file
[File-edi.txt](https://github.com/DonZoeggerle/ediFabric/files/838258/File-edi.txt)

**Comment by DonZoeggerle** [comment]
Parsed it fine with version 7.3.0
